-- Run this in Supabase SQL Editor to enable click analytics storage.

create table if not exists public.click_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  event_label text,
  source_page text,
  product_name text,
  shop_key text,
  product_index text,
  target_url text,
  phone_number text,
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.click_events enable row level security;

-- Allow public website visitors (anon key) to insert click events.
drop policy if exists "Allow anon insert click events" on public.click_events;
create policy "Allow anon insert click events"
on public.click_events
for insert
with check (true);

-- Optional: allow authenticated users to read events in dashboard tools.
drop policy if exists "Allow authenticated read click events" on public.click_events;
create policy "Allow authenticated read click events"
on public.click_events
for select
using (auth.role() = 'authenticated');
